version: '3.8'

services:
  lcdi-facturation:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=votre_cle_secrete_production_changez_moi
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
