version: '3.8'

services:
  lcdi-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-me}
      - PORT=5000
      - MAX_CONTENT_LENGTH=50000000
    volumes:
      # Monter les dossiers pour persister les données en développement
      - ./uploads:/app/uploads
      - ./output:/app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    container_name: lcdi-compta-app

  # Service optionnel pour un reverse proxy en production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - lcdi-app
    restart: unless-stopped
    container_name: lcdi-nginx
    profiles:
      - production

networks:
  default:
    name: lcdi-network
